### PR TITLE
feat(content): electric powered air pump for pneumatic weapons

### PR DESCRIPTION
**Pull request by Soadreqm**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Homemade pneumatic weapons take a really long time to reload, representing how you need to pump up the air pressure to make them usable. This adds a craftable weapon mod that greatly shortens the reload time but also consumes UPS charge, representing an electric pump that keeps the air tank pressurized automatically.

## Describe the solution
The powered air pump cuts down reload time to one fifth, which is 120 units per ammo for the pneumatic assault rifle and bolt driver, and 1200 for the shotgun. It consumes 40 UPS charge per shot. Unfortunately the charge is consumed when firing, not when reloading. It is what it is.

You can attach the mod, reload the gun and remove the mod again for no UPS cost, which is a bit silly, but gives no actual benefit. Attaching the mod takes more time than just reloading by hand, so you can't do it in combat. 

## Describe alternatives you've considered
In an ideal world, the game would actually track the air pressure in the gun's tank, and it would affect damage and range of each shot, but that sounds like a lot of work for not much benefit.

~~60 UPS charge is the same as the ferromagnetic rail rifle uses. Pneumatics do less damage, but it seems like a safe bet that using electricity to fill an air tank to push a projectile would be less efficient than just using electricity to push a projectile. Also I don't want to create a situation where the rail rifle is a downgrade from the pneumatic bolt driver.~~
See discussion for further alternatives considered.

## Testing
Crafted and attached the mod to the pneumatic assault rifle, bolt rifle and shotgun. Verified that reload time was shorter, that UPS charge was consumed when firing, and that the weapons could not be fired without UPS until the mod was removed.

### CODE REVIEW

**Comment by yay855** [comment]
My main complaint is that you're comparing the energy it takes to launch a massive hunk of rebar using magnetic forces entirely, to the amount of energy it takes to pressurize an air chamber enough to launch a ball bearing at high speeds. Railguns are intended to be strong but costly, while this weapon mod adds in the same cost to a pneumatic weapon without really making it hit that much harder. I'd suggest cutting the actual UPS cost per shot down to, say, 15-30 to justify the fact that you're not putting nearly the same amount of energy into launching a ball bearing as you are to launching rebar, as reflected by the damage of those weapons.

**Comment by Soadreqm** [comment]
> My main complaint is that you're comparing the energy it takes to launch a massive hunk of rebar using magnetic forces entirely, to the amount of energy it takes to pressurize an air chamber enough to launch a ball bearing at high speeds. 

Yeah, I looked at the bolt driver numbers more. The rail rifle firing rebars does 80 damage, which at 60 kJ gives it 1.33 d/kJ. The Helsing with broadhead bolts does 55 damage, or 0.92 d/kJ. That seemed like a reasonable ratio to me - the rail rifle should be better at converting electric power into kinetic energy, since it's not wasting it with the intermediary air compression.

It is admittedly pretty bleak for the pneumatic assault rifle, which only does 0.35 d/kJ with steel ball bearings.

I actually made a whole table. For broadhead bolts and ball bearings respectively:
```
Energy Helsing  Tihar
20      2.75     1.05
30      1.83     0.70
40      1.38     0.53
50      1.10     0.42
60      0.92     0.35
70      0.79     0.30
80      0.69     0.26
90      0.61     0.23
```
For further context, the homemade coilgun that shoots nails does 1.20 d/kJ and the H&K G80, a bit of an outlier, does 10.0 d/kJ.

Anyway. I feel like there shouldn't be a scenario where a pneumatic weapon is more efficient than a railgun, but if the pneumatic power use was dropped to 40, they'd be basically even for the pneumatic best case. Marginally more damage per joule for the Helsing, but no armor piercing, and less range. Another option would be to start over, and just add separate items for the electric powered air guns, with their own crafting recipes. I don't want to - I really like the concept of gun mods that fundamentally alter how the weapon works - but it would allow giving them different power requirements.

**Comment by chaosvolt** [comment]
Personally I have to agree with the feedback that 60 might be a bit high for these weapons. 40 as you noted is about break-even, so I'd be okay with that. 50 I guess is a lil better, that also makes it easier to determine how many shots you get with a given battery in a UPS.

**Comment by Soadreqm** [comment]
Dropped it to 40.

**Review by chaosvolt — DISMISSED** [review]
Think that should work aight then.

**Review by ghost — DISMISSED** [review]
Why not.

**Comment by RoyalFox2140** [comment]
There was a merge conflict. I should've solved it but I'm double checking because of the web UI.

**Review by ghost — APPROVED** [review]
Should be good now that the merge conflict is resolved.

**Comment by H-Sharp** [comment]
Shouldn't an electric air pump add a lot of noise? The drawback of the pneumatic is the long reload time, but you get a pretty nice silenced weapon. If you are taking away the reload time (yes needing a big old UPS) it feels it shouldn't be so silent anymore.

**Pull request merged**
