### PR TITLE
feat(balance): adjust coilgun recipe

### PR DESCRIPTION
**Pull request by Soadreqm**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
The coilgun crafting recipe seemed a bit off. Despite it being an electrical device, It uses fabrication as the primary skill, and has mechanics and electronics as additional requirements, with mechanics at a _higher_ level than fabrication. The material requirements are quite a bit lower than the shoddy laser rifle, which is otherwise around the same tier, and it doesn't require a UPS mod which is used in crafting every other energy weapon.

## Describe the solution
Made electronics the primary skill and increased difficulty from 4 to 5, with mechanics 5 and fabrication 4 as secondaries. For materials, made it use additional power converter, electronic scrap, copper wire and a UPS mod. Also replaced requirement for pipe with plastic chunks, since I'm pretty sure you can't put a barrel made of ferromagnetic material on a coilgun and have it work.

## Describe alternatives you've considered
Originally part of #5590, split to its own PR.

## Testing
Loaded game with no errors, looked at coilgun recipe in crafting menu.

### CODE REVIEW

**Review by chaosvolt — COMMENTED** [review]
Looks aight. Only thing I might note is that the light railgun uses 80 copper wire, so it might be more consistent with a lower amount since it has less punch, though increasing the amount used to make the rebar rifle is also reasonable (for reference the heavy rail rifle uses 240 wire so there's a lot of space here).

**Comment by Soadreqm** [comment]
I figured it wouldn't use as much, since it's specifically fluffed as a *rail*gun, rather than a *coil*gun. No coils, just a pair of conductor rails.

On the other hand, the heavy railgun clearly does use a shitton of wire, so maybe a more linear progression would make sense. Maybe bump the coilgun down to 80 wire, and the light railgun up to 140?

**Comment by RoyalFox2140** [comment]
More wire is always great! Copper wire isn't hard to get a lot of, it's either a loot drop you get commonly from houses thanks to spawning with TV's or you scrap a bunch of stuff.

**Comment by Soadreqm** [comment]
As another alternative, could replace some of the wire requirement in the railguns with pure copper. It's easier to source than wire, but I think it could do with having a few more uses besides primitive metalcrafting.

**Review by chaosvolt — APPROVED** [review]
:>

**Pull request merged**
