### PR TITLE
feat(port): Add eBook reader to Store / Read books

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
SUMMARY: Features "[Port] Add eBook reader to Store / Read books"

#### Purpose of change
The ability to store books content on an electronic device would give players that reached mid to late game an excellent alternative to carry all of their books on them.
Perfect for nomadic playthrough.
The books would still have some advantages though, because NPCs can't read eBook, and books don't require power.

#### Describe the solution
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/49408
Also, this branch is branched of #2170 (I needed some changes in it).

#### Describe alternatives you've considered
I first wanted to port https://github.com/CleverRaven/Cataclysm-DDA/pull/46304, but I after a long reflexion I thought it would probably be easier to port only the eBook one.
If someone has the time and the knowledge to do it though, it would be a great idea.

#### Testing
Here's the catch, keeping in mind that it's a work in progress.
- scan a book
- it consumes power, the book is stored
- open the read menu
- the new book appear
- select it
- you're now reading the book
- the screen is automatically switched on, everything is as usual (experiene increase, recipes learnt, level up..)
- then you keep the benefits of your reading as usual
- there's a function that I didn't implement yet, to get recipes from ebooks around you when you open the crafting menu, but that's not what I'm worried about
- no what worries me, is that when you reload a save, you have a high chance of save corruption
- now I may be just tired and it's a simple fix, but if someone wants to help, I'm not against it

#### Additional context
A big thanks to Saicchi and Night-Pryanik for the original PR.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Would you mind adding the original authors of the PR's you are porting as Co-authors?  It's super easy in Github Desktop and it will get your attribution fixed up.  I saw you thanked Saichi and Night but didn't credit them.

**Comment by leoCottret** [comment]
> Would you mind adding the original authors of the PR's you are porting as Co-authors? It's super easy in Github Desktop and it will get your attribution fixed up. I saw you thanked Saichi and Night but didn't credit them.

Ok it's done.
Thanks for reporting the fact that I didn't correctly credit their work.
Until then I just added the link to the original PR(s), but from our discord discution, it seems that it wasn't the best way to do it.

If someone is in the same situation as me, you can just add a dummy commit and credit the coauthors in it.
Then when it's merged the coauthorship can be added on the important commit(s).

**Comment by scarf005** [comment]
hello, it's been a few month since this PR was open, are you interested in continuting the PR?

**Comment by Lamandus** [comment]
closed due to lacking activity. Already lacking behind codewise a lot.

**Pull request closed without merging**
