### PR TITLE
feat(content): make sheets of metal and wood stackable

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
Make also steel sheets (big and small), and big wooden panels stackable, since, they can be... stacked.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
goofy ahhh stacks

**Comment by chaosvolt** [comment]
2 years later and we discovered that this change made quarterpanels and roofs completely invulnerable, oooof. Now trying to figure out the most graceful way to unfuck that. XD

**Comment by Lamandus** [comment]
> 2 years later and we discovered that this change made quarterpanels and roofs completely invulnerable, oooof. Now trying to figure out the most graceful way to unfuck that. XD

not something I expected to happen. hah

**Comment by scarf005** [comment]
related: #8859

**Pull request merged**
