### PR TITLE
feat(balance): crafting energy weapons requires special components

### PR DESCRIPTION
**Pull request by Soadreqm**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
The shoddy laser rifle ~~and the coilgun~~ are too easy to make. They can be crafted from common electrical components at only moderate skill level - electronics 5 for the laser, ~~and fab 4 mech 5 elec 4 for the coilgun, and you can actually make the coilgun at fab 3 and no other skills if you have one of the books with the crafting recipe.~~ You literally just have to find two books and a soldering iron, and disassemble a few computers.

While making them doesn't have to be a massive chore, it should require effort commensurate to the utility of the weapons. Despite the low damage, they're both very useful, making almost no noise and even the coilgun having very little recoil.

## Describe the solution
Added new electrical components: industrial lasers and high-energy capacitors. Lasers can be acquired from: 
- disassembling the dissector traps found in labs  
- disassembling laser surgery machines that have been added in hospitals
- disassembling industrial laser cutters that have been added in the steel mill
- by smashing an autodoc
- randomly found with other electronics drops at a fairly low chance

~~Any machine that has an industrial laser will likewise have some amount of capacitors. Additionally, capacitors can be acquired from:~~
- ~~disassembling the capacitor banks found in wind turbines.~~
- ~~disassembling electronic machinery found in a lot of places~~
- ~~disassembling current transformers mostly found in power substations~~

The shoddy laser rifle requires a single laser source, ~~and electromagnetic weapons use high-energy capacitors - 6 for the coilgun, 8 for the rail rifle and 12 for the heavy rail rifle.~~

~~Also, the wind turbine capacitor bank can now be deconstructed as well as smashed. Maximum item yields for bashing reduced to about half, except for scrap metal which was increased instead. Maximum item yields for disassembly are what bash yields used to be, minimums set to about half that.~~

~~Further adjusted coilcun recipe to be more consistent with other energy weapons. Now has electronics as main skill and fabrication as secondary; requires additional power converter, electronic scrap, copper wire and a UPS mod. Pipe requirement replaced with plastic chunks since I'm pretty sure you can't put a barrel made of ferromagnetic material on a coilgun and have it work.~~

## Describe alternatives you've considered
Initially planned to make the dissector turn into furniture when deactivated, but that's currently not possible. It _would_ be possible to just make it drop the components, instead of an item that deconstructs into components, but that feels a bit too easy. It should take some amount of time and effort to disassemble sophisticated machinery.

I gave the dissector a disarm difficulty of 2, which is quite easy but not guaranteed. As I understand it's not really meant to be a trap, just a very unsafe piece of scientific equipment, so maybe it should be guaranteed. While testing, I managed to disarm it with zero traps skill, but it took a few tries, and I find it amusing to imagine my character lasing himself like an idiot while trying to turn it off. Failures were painful, but not fatal.

~~Thought about adding some kind of industrial laser cutter machine to the steel mill,~~ _done_ and/or the lab variants that don't spawn dissectors. Could be done in the future.

## Testing
Loaded game with no errors, disarmed dissectors in a lab and then disassembled the broken dissectors. ~~Disassembled and smashed capacitor banks in a windmill.~~ Constructed a laser rifle ~~and a coilgun~~.

### CODE REVIEW

**Comment by yay855** [comment]
My primary complaint is that the shoddy laser rifle and coilgun aren't actually that amazing as weapons, and already rely on the player having access to a UPS and a ton of large batteries (or a UPS bionic and a ton of internal battery), locking them to being post-lab seems a bit silly when you can get a repeating crossbow or a pneumatic assault rifle or even just an AR15 long before then.

**Comment by RoyalFox2140** [comment]
This seems like a solution in search of a problem. Lasers are in a weird spot where the good ones are an incredibly rare energy devouring device that struggles to find a good use case given the ease of making a longbow or greatbow, or finding a compound bow, which itself has no noise and great range.

I would prefer instead to add noise to all lasers because bows and crossbows should be the only weapon without noise. Monsters can't fight back when a weapon doesn't make noise and the light generation is not sufficient.

**Comment by RoyalFox2140** [comment]
Regarding components:
image

This is actually a bit harder than one might think and we desire to make resources a little more scarce soon too. 200 solder is a lot and it makes you have a forging setup or a lot of spare electronics, High quality lenses are fairly uncommon and require things like professional cameras, smartphones only drop small ones. I gave it quite a bit of thought on how this would fit into the game when I ported it from Aftershock.

**Comment by chaosvolt** [comment]
I'm not sure this is a good idea either. If the components could be found in other logical sources maybe, but in its current form it's a bit pointless restricting two fairly mediocre UPS weapons behind material you can only find from basically a single trap and a single furniture, both of which aren't very common (plus this makes it much less intuitive to find them).

The skill increases in your recipe change seem acceptable, just the component idea is not well-implemented in my opinion.

**Comment by RoyalFox2140** [comment]
> Further adjusted coilgun recipe to be more consistent with other energy weapons. Now has electronics as main skill and fabrication as secondary; requires additional power converter, electronic scrap, copper wire and a UPS mod. Pipe requirement replaced with plastic chunks since I'm pretty sure you can't put a barrel made of ferromagnetic material on a coilgun and have it work.

I think this coilgun adjustment to a plastic barrel and the skill flipping to electronics is good, I'd like to see that in a separate PR if this one isn't merged, I think since it's comparable to shoddy laser rifle which now is mainlined it's good to keep them internally consistent.

**Comment by Soadreqm** [comment]
Well, the main utility of the shoddy laser rifle is that you can mount it on a turret and have it run off vehicle power. If you further add a turret control system (computer 4, mechanics 3, requires parts salvaged from a robot or an enemy turret), it will delete any enemy that enters a 25 tile radius. And like... that _should_ be possible, it's fun to see the different systems interact, but it feels a bit too easy right now.

Also, I just find it offensive that I'm able to disassemble a bunch of computers and reassemble them into a high-powered laser. There should be a delineation between things you can craft from raw materials with enough effort, and irreplaceable pre-cataclysm archaeotech. Maybe that's just a me problem? Anyway, I don't mind making the parts more common, if that's the prevailing opinion, but I'd prefer to have them exist.

An industrial laser cutter is the obvious option, but the steel mill is pretty rare and I can't think of any other industrial locations where you'd expect to find one. Instead I could:
- Add a surgical laser machine, appears in hospitals and bionic clinics
- Add lasers and capacitors to the `elecsto_diy` itemgroup, dropping at electronics shops
- Add broken dissectors to the `recycle_electronic` and `oa_ig_rd_electronic_trash` itemgroups (at a fairly low probability), dropping at recycling centers and regional dumps respectively
- Make at least one of the machines found at a power substation provide capacitors

That'd be two more guaranteed locations to find the lasers, three to find capacitors, and a few non-guaranteed locations to go look for them. Would that be more reasonable?

**Comment by RoyalFox2140** [comment]
> Well, the main utility of the shoddy laser rifle is that you can mount it on a turret and have it run off vehicle power. 

I am 100% okay with either:
Banning the use of shoddy laser rifles on cars (A final resort if we cant reconcile problems)

Increasing all laser power draw until it's not the mega problem it is, or instating some period of cooldown on lasers firing on top of vehicles Perhaps vehicle power draw is higher because of issues like cooling.

**Comment by RoyalFox2140** [comment]
> Also, I just find it offensive that I'm able to disassemble a bunch of computers and reassemble them into a high-powered laser.

You need high quality lenses from professional cameras. See previous post. This directly competes with placing security cameras on your car. 

> Add lasers and capacitors to the elecsto_diy itemgroup, dropping at electronics shops

This is where the lenses come into play. I'm willing to look over the components but:

"Capacitors" exist. Those are electronic scrap.
Diodes exist, those are electronic scrap. An "industrial laser" isn't really a thing, its a number of components put to make a laser.
The components should be in as many locations as possible that make sense. 

Instead of "high-energy capacitors" used only for one weapon, I would instead do something like a "capacitor array" made from a significant amount of effort and existing components, which would be used in all sorts of electronic recipes from now on and come from a lot of other locations like power stations in addition to labs, hospitals, clinics, recycling centers, dumps, electronics stores. Capacitor arrays could be used on a lot of things, but including air conditioners. It would help if either pre-cataclysm capacitors would spawn damaged given their age or that you can't salvage a capacitor array (or items with said capacitors) to get all the scrap back given same issue of age. Air Conditioners IRL often have capacitors fail for example.

The high quality lenses are overlooked. We could upgrade the cost of those to 5, do a separate lens for magnifying glasses and binoculars so it forces it to be from camera's or robots, and possibly make them harder to recover intact since robots always have damage from combat.

I think we need to look over the whole electronics system. You want to make lasers less of something you stumble into but I think we should accomplish that by instead making electronics in general something you don't sneeze and get an electric forge immediately.

**Comment by Soadreqm** [comment]
@RoyalFox2140 
>200 solder is a lot and it makes you have a forging setup or a lot of spare electronics, High quality lenses are fairly uncommon and require things like professional cameras, smartphones only drop small ones.

It's not that much. 200 solder is the default stack amount, so if you find solder at an electronics shop, a random basement or the body of a zombie technician, you're set. Well, almost, you need a bit more for the UPS mod. CPU, RAM and small LCD screen all give 5, so you get 15 total from a smartphone. A broken console gives (on average) 1.5 processors, 6 ram, 3 amplifiers (4 solder) and a large LCD screen (15 solder), for 64.5 solder total.

Lenses can also be acquired from binoculars, non-professional cameras and all robots. They're not super common, but you're pretty likely to find some without especially looking for them.

>I am 100% okay with either:
>Banning the use of shoddy laser rifles on cars (A final resort if we cant reconcile problems)
>Increasing all laser power draw until it's not the mega problem it is, or instating some period of cooldown on lasers firing on top of vehicles Perhaps vehicle power draw is higher because of issues like cooling.

Thing is, I don't feel like there's any reason why it _shouldn't_ work. Being able to mount a laser on a car is just a consequence of having an internally consistent world with both lasers and cars, and most lasers are adequately balanced by the fact that you can't find them. It's just that this one laser is craftable, and not very hard to craft.

**Comment by KheirFerrum** [comment]
Honestly sounds more like an issue with zombie swarms not being a danger to cars. There's no real difference between this and mounting a 9mm turret onto your car and reloading the brass between encounters. I don't _necessarily_ think this makes a whole lot of sense.

If your issue is that lasers are too high tech for pre-lab examples, then they'll need to be buffed and not be called "shoddy" laser rifles.

**Comment by KheirFerrum** [comment]
To recap on a conversation held in Discord.

> Add a surgical laser machine, appears in hospitals and bionic clinics
> Add lasers and capacitors to the elecsto_diy itemgroup, dropping at electronics shops
> Add broken dissectors to the recycle_electronic and oa_ig_rd_electronic_trash itemgroups (at a fairly low probability), dropping at recycling centers and regional dumps respectively
> Make at least one of the machines found at a power substation provide capacitors

I'm good with most of this, recycling centres and regional dumps probably wouldn't get whole dissectors, given the secretive nature of them. But surgical lasers and the like could, capacitors in industrial zones could also be a thing, I'm wondering if we'd have them for electric cars, but that's a discussion for another time.

I'd keep the skill levels as is as the player is largely assembling pre-fabricated components rather than making their own laser diode from scratch, a separate recipe for that could be made if desired.

**Comment by Soadreqm** [comment]
Additional item drops.
- The 3x3 hospital, the 2x2 tall hospital and augmentation clinic have a single laser surgery machine each. The 1x1 doctor's offices do not.
- Steel mill has two industrial laser cutters. (The conveyor belt was two tiles wide.)
- Added laser and capacitor items to the `elecsto_diy` list, but it didn't look like that was pulled from very often, so I also added them to the general `electronics` list. While testing, the very first electronics store I teleported to had a laser source, and then the next seven or so didn't, so it seems like item drops are a crapshoot as intended.
- Smashing an autodoc has a chance to drop a laser and a couple capacitors. Not really intended as a reasonable way of getting them, more in case one gets smashed by zombies.
- Electronic machinery has a 50% chance to drop a capacitor when deconstructed. It's not defined what it is, so might as well. 
- The current transformer has a 100% chance to drop 3. It's not something you'd find inside a real current transformer, as far as I can tell, but there was a nice amount of them at the power stations and the old disassembly results were kind of lame. I think this is better than adding capacitor banks to power stations because A) capacitor banks explode even though the substation has no power and B) current transformers already appear in a few other industrial locations, like the irradiation plant, so that's a freebie.

**Comment by ZChris13** [comment]
My thoughts: the coilgun is really extremely good, especially using flechettes, especially for how cheap the ammo is
compared to something like an AR-15 or carbon fiber assault rifle it's not amazing but building it only barely requires leaving the starting shelter
giving the magnetic weapons recoil would go a long way to making it feel more balanced and "real", if you want to leave the crafting requirements as they are without salvaging any high power capacitors from labs and such
the high power capacitors is a great idea however, I think it would be cool if it was worked into a high skill weapon mod that you could craft that would take the coilgun from good to great
I approve of making the laser rifle require salvaging laser-specific drops from high tech locations

**Comment by Pr0man** [comment]
Welp, time to add my two cents to the entire discussion, since I do play with a lot of energy weapons - because I love having access to craftables in that context... And I have to say that at that point you might as well remove these two guns, because your change is effectively doing that by itself.

The entire draw of these weapons is that they are relatively cheap to craft, but do not perform exceptionally well when compared to actual firearms. From a raw damage perspective, they lie somewhere in the realm of .22 LR, which is infamous in the cataclysm community for being left behind, dismantled for its powder or used to train your weapon skills due to it being common and weak. Not to mention these guns are requiring quite a bit of overhang in form of a UPS with appropriate batteries and ways to charge them, or the UPS CBM with storage and ways to generate Bionic Energy at any resonable rate. By making the components effectively lab loot - because hospitals are prone to losing their equipment to the rampaging zombie hordes inside and steel mills are absolutely overrun by mid to high tier zombies - or rare component drops, you will have obsoleted them already. It is very easy for players to have amassed an arsenal to clear out a town by virtue of gunpowder simply by looting most houses, let alone gun stores and by the time normal players tackle a lab, that arsenal is only growing in size and firepower.

The fault doesn't exactly lie in the weapons being powerful for how easy they are to craft. Anyone using them on foot regularly could attest to that: At a power draw of 30 for the shoddy laser and 20 for the nail rifle, you have 33 and 50 shots respectively, assuming a heavy battery for your UPS. That is comparable to an assault rifle and those deal way more damage across the board. The benefits here are silent shots, with the added niche that the Coilgun has is that it also comes with some really good armor piercing at 23 (assuming nails), meaning it deals steady damage for using dirt cheap ammo unless you face kevlar hulks on a regular basis.

The issue lies rather in the absurd availability of renewable power. Solar panels provide an absurd amount of free energy to grids (8 times that of a small wind turbine, with solars giving 80 epower, small wind turbines 10) and some town buildings are absolutely littered in these things. Solar cars can be found pretty commonly as well and that means panels as well as batteries are basically thrown after the player - the easiest and most powerful renewable power if we talk finding and not crafting - so that encourages players to naturally drift towards energy weapons because there is absolutely no downside to using them and the energy is abundant anyways. It isn't exactly uncommon to hear that people make absurdly powerful solar death mobiles because they found so many solar panels on the roadside, by simply having all their vehicle roof tiles covered in the solars and advanced solars you come across and deciding to see if they could run their gunbrick on electric engines.
If energy wasn't just practically infinite to even the most basic players that manage to establish a small power grid (or play as an evacuee since the shelter gives you a free functioning grid with charger!), using these guns wouldn't be such attractive alternatives that you could just slap a bunch of those onto your mobile fortress and clean out towns without it even registering on your vehicles battery charge as so much of a blip that is recovered within a day or two.

**Comment by Soadreqm** [comment]
@Pr0man 
>By making the components effectively lab loot - because hospitals are prone to losing their equipment to the rampaging zombie hordes inside

Well, the 3x3 hospital has two autodocs in addition to the surgical laser, so if zombies smash them all, that's a 87.5% chance to get a laser. Also, if this is the root of the problem, I could just make the laser drop guaranteed when smashing one of those. Others have complained about being unable to find a hospital, but you get directions to one from a quest at the refugee center, so that should be guaranteed too.

Also, Kheir suggested axing the capacitors entirely and only adding lasers, and though I haven't done that yet, it would mean you could still make the coilgun out of computer parts.

**Comment by ZChris13** [comment]
> but do not perform exceptionally well when compared to actual firearms. From a raw damage perspective, they lie somewhere in the realm of .22 LR

anybody who says something like this obviously has never used the coilgun lmao, witness as it outclasses M855 vs kevlar hulks
image

**Comment by RoyalFox2140** [comment]
> anybody who says something like this obviously has never used the coilgun lmao, witness as it outclasses M855 vs kevlar hulks 

Stay respectful in PR discussion.

**Review by scarf005 — COMMENTED** [review]
the changes feel too controversial, and personally i'm not into creating components for the sake of making an item harder to craft. however it's just a personal opinion; i'll ask for @Coolthulhu for final thoughts.

**Comment by Soadreqm** [comment]
Removed capacitors. Does anyone have any other suggestions, or is the idea categorically unworkable?

**Comment by ZChris13** [comment]
I quite like this now

**Review by Coolthulhu — APPROVED** [review]

**Comment by RoyalFox2140** [comment]
Ok, Coolthulhu has greenlit it so I'm merging since all tests pass.

**Pull request merged**
